version: 2.1

orbs:
  node: circleci/node@5.2.0

aliases:
  - &docker_image
    - image: cimg/base:stable

  - &current_workspace
    attach_workspace: { at: '.' }

jobs:
  install-dependencies:
    docker: *docker_image
    steps:
      - checkout
      - node/install:
          node-version: '20.16.0'
      - run: node --version
      - node/install-packages
      - persist_to_workspace:
          root: '.'
          paths:
            - 'node_modules/*'

  static-validation:
    docker: *docker_image
    steps:
      - checkout
      - *current_workspace
      - run:
          name: Format Check
          command: npm run format:check
      - run:
          name: Lint Check
          command: npm run lint

workflows:
  test_my_app:
    jobs:
      - install-dependencies
      - static-validation:
          requires:
            - install-dependencies
