version: "3.8"

services:
  legacy_database:
    image: mysql:5.7
    container_name: legacy_database
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "sisautoescola"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - legacy-network

  legacy_system:
    container_name: legacy_system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./sisautoescola:/var/www/html
    networks:
      - legacy-network
    depends_on:
      - legacy_database

networks:
  legacy-network:
    driver: bridge
